# これらのオプションをサポートしたい場合は、コメントを外してください
# github: nezumi0627
# patreon: nezumi0627
# open_collective: nezumi0627
# ko_fi: nezumi0627
# liberapay: nezumi0627
# issuehunt: nezumi0627
# otechie: nezumi0627
# lfx_crowdfunding: nezumi0627
# custom: ['https://your-donation-link.com']

